# Generated by Django 4.1.3 on 2022-11-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(help_text='Ingrese el nombre de la comuna', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IniciaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese sus nombres', max_length=20)),
                ('apellido', models.CharField(help_text='Ingrese sus apellidos', max_length=40)),
                ('rut', models.CharField(help_text='Ingrese su RUT sin puntos ni guión', max_length=10)),
                ('contraseña', models.CharField(help_text='Ingrese su contraseña', max_length=50)),
                ('fecha_nac', models.DateField(help_text='Ingrese su fecha de nacimiento')),
                ('correo', models.EmailField(blank=True, help_text='Indique un correo válido', max_length=254)),
                ('telefono', models.PositiveIntegerField(help_text='Ingrese el Numero de telefono')),
                ('direccion', models.CharField(blank=True, help_text='Ingrese su dirección (Calle y número)', max_length=45)),
                ('funcionario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(help_text='Ingrese el nombre de la Region', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(help_text='Ingrese el nombre del Rol', max_length=20)),
                ('lectura', models.BooleanField(default=False)),
                ('Escritura', models.BooleanField(default=False)),
                ('Edicion', models.BooleanField(default=False)),
                ('Borrar', models.BooleanField(default=False)),
                ('Crear', models.BooleanField(default=False)),
            ],
        ),
    ]
